### PR TITLE
fix: handle base64/58 decode errors gracefully

### LINKED ISSUE #68: Fix base64/58 error handling
## Problem: 

CLI exits when empty or invalid base64/58 is passed to send tx and yet it prints as done.

## Solution:

Handle error & loop back to take input, without exiting.

## Screenshot of the issue:

Image

### PR DESCRIPTION
**Pull request by Anantdadhich**
Fixes CLI behavior when invalid or empty base64/58 input is passed to Send Transaction.

Closes #68 

Issue-
Previously, the CLI displayed “✅ Done” even when decoding failed, and then exited with an error afterward.

Fix-
The CLI now validates the encoded transaction input and, on decode failure (or empty input), shows a clear error message and re-prompts the user until a valid encoded transaction is provided.

Now showing - 
 Enter encoded transaction: sdfasdfasdf
Error: Failed to decode Base64: Invalid padding...
Please enter a valid encoded transaction.
? Enter encoded transaction:

### CODE REVIEW

File: src/commands/transaction.rs [hunk 1]
```diff
@@ -91,13 +91,86 @@ impl TransactionCommand {
...
+                            );
+                            println!(
+                                "{}",
+                                style("Transaction failed. Please try again.")
+                                    .yellow()
+                            );
+                            continue;
+                        }
+                    }
+                }
```
Comment (Nagaprasadvr) [inline src/commands/transaction.rs]: revert - we should propogate the error

File: src/commands/transaction.rs [hunk 2]
```diff
@@ -295,21 +368,11 @@ async fn process_fetch_transaction(
     Ok(())
 }
 
-async fn process_send_transaction(
+async fn send_validated_transaction(
```
Comment (Nagaprasadvr) [inline src/commands/transaction.rs]: revert these changes

**Review by BretasArthur1 — APPROVED** [review]
